### PR TITLE
Feat: Remove the /hapi/ UI and migrate all functionality into WebRPC + lit mjs

### PR DESCRIPTION
**Pull request by snadrus**
Feat: Remove the /hapi/ UI and migrate all functionality into WebRPC + lit mjs

### CODE REVIEW

**Comment by magik6k** [comment]
> The only 'hapi' ref is in index.html:
>       `<tbody hx-get="/hapi/simpleinfo/actorsummary" hx-trigger="load,every 5s">`

A rebase will fix this now

**Comment by snadrus** [comment]
I completed testing in my local environment but with so many blanks it could have issues rendering things when [].length > 0

**Review by LexLuthr — CHANGES_REQUESTED** [review]
This breaks docker devnet logs. Although the Curio node is started in the end correctly. Not sure what's going on here. 

```
2024-07-24 14:18:33 The head is now greater than 9: 10
2024-07-24 14:18:33 All ready. Lets go
2024-07-24 14:18:33 Wait for lotus-miner is ready ...
2024-07-24 14:18:33 Create a new miner actor ...
2024-07-24 14:18:33 2024-07-24T10:18:33.863Z    INFO    lotus-shed      lotus-shed/miner.go:346 Pushed CreateMiner message: bafy2bzacebcl4tfyr2ric3ph7m6nhn4d6ajeog24esewnxmmh3fjti5v3cno6
2024-07-24 14:18:33 2024-07-24T10:18:33.863Z    INFO    lotus-shed      lotus-shed/miner.go:347 Waiting for confirmation
2024-07-24 14:19:01 2024-07-24T10:19:01.006Z    INFO    lotus-shed      lotus-shed/miner.go:363 New miners address is: t01002 (t2snmkjqamg4afxwwwh4amuubfuwiv5eyqhhhoy6y)
2024-07-24 14:19:01 New Miner is t01002
2024-07-24 14:19:01 Initiating a new Curio cluster ...
2024-07-24 14:19:33 The base layer has been updated with miner[s] [t01002]
2024-07-24 14:19:33 Enabling market ...
2024-07-24 14:19:33 Layer seal created/updated
2024-07-24 14:19:33 Starting Curio node to attach storage ...
2024-07-24 14:19:33 repopath /var/lib/curio
2024-07-24 14:19:33 ERROR: querying version: RPC client error: sendRequest failed: Post "http://172.20.0.4:12300/rpc/v0": dial tcp 172.20.0.4:12300: connect: connection refused
2024-07-24 14:19:33 
2024-07-24 14:19:33 Waiting for the curio CLI to become ready...
2024-07-24 14:19:38 remote node version: [1 22 1]
2024-07-24 14:19:38 remote node version: [1 22 1]
2024-07-24 14:19:38 Stopping Curio node ...
2024-07-24 14:19:38 Try to stop boost...
2024-07-24 14:19:38 Done
2024-07-24 14:19:38 Starting curio node ...
2024-07-24 14:19:38 
- Ctrl+C pressed in Terminal
2024-07-24 14:19:38 repopath /var/lib/curio
```

**Comment by LexLuthr** [comment]
Found the following issues in UI:

1. PoRep pipeline is complete empty

Screenshot 2024-07-24 at 2 35 33 PM

2. 24 hour task count is below recently finished

Screenshot 2024-07-24 at 2 34 41 PM

3. Home page PoRep pipeline table is messed up


Screenshot 2024-07-24 at 2 34 28 PM


5. Deal menu item is not aligned
Screenshot 2024-07-24 at 2 35 04 PM

**Comment by LexLuthr** [comment]
In the "Node" page, we should align all 4 tables in 2x2 grid. It would save space and reduce unnecessary scrolling.

**Review by LexLuthr — APPROVED** [review]

**Comment by LexLuthr** [comment]
I have fixed all the issues I found. 2 remaining things I punted are:
1. Sector list filter based on miner ID
2. Rearrange node details and home page to be less cluttered.

**Pull request merged**
