### PR TITLE
feat: Add support for Prometheus AlertManager

### PR DESCRIPTION
**Pull request by strahe**
https://github.com/filecoin-project/curio/discussions/83

Added support for the [Prometheus AlertManager](https://github.com/prometheus/alertmanager), resulting in a change to the configuration file format:

Previously:
```go
type CurioAlerting struct {
    // PagerDutyEventURL is the URL for PagerDuty.com Events API v2. Events sent to this API URL are ultimately
    // routed to a PagerDuty.com service and processed.
    // The default is sufficient for integration with the stock commercial PagerDuty.com company's service.
    PagerDutyEventURL string

    // PageDutyIntegrationKey is the integration key for a PagerDuty.com service. You can find this unique service
    // identifier on the integration page for the service.
    PageDutyIntegrationKey string

    // MinimumWalletBalance is the minimum balance for all active wallets. If the balance is below this value, an
    // alert will be triggered for the wallet.
    MinimumWalletBalance types.FIL
}
```
Now:
```go
type CurioAlertingConfig struct {
    // MinimumWalletBalance is the minimum balance for all active wallets. If the balance is below this value, an
    // alert will be triggered for the wallet.
    MinimumWalletBalance types.FIL

    // PagerDutyConfig is the configuration for the PagerDuty alerting integration.
    PagerDuty PagerDutyConfig

    // PrometheusAlertManagerConfig is the configuration for the Prometheus AlertManager alerting integration.
    PrometheusAlertManager PrometheusAlertManagerConfig
}

type PagerDutyConfig struct {
	// Enable is a flag to enable or disable the PagerDuty integration.
	Enable bool

	// PagerDutyEventURL is URL for PagerDuty.com Events API v2 URL. Events sent to this API URL are ultimately
	// routed to a PagerDuty.com service and processed.
	// The default is sufficient for integration with the stock commercial PagerDuty.com company's service.
	PagerDutyEventURL string

	// PageDutyIntegrationKey is the integration key for a PagerDuty.com service. You can find this unique service
	// identifier in the integration page for the service.
	PageDutyIntegrationKey string
}

type PrometheusAlertManagerConfig struct {
	// Enable is a flag to enable or disable the Prometheus AlertManager integration.
	Enable bool

	// AlertManagerURL is the URL for the Prometheus AlertManager API v2 URL.
	AlertManagerURL string
}
```

### CODE REVIEW

**Comment by strahe** [comment]
Hi, @LexLuthr, this pr ready for review

**Review by LexLuthr — COMMENTED** [review]
Code looks good!
I would ask if you could add a doc like https://github.com/filecoin-project/curio/blob/main/harmony/harmonytask/doc.go detailing how to add new plugins? I think it would be really helpful for others who might want to add another one.
Also, can you please test this and attach screenshots of prometheus alert?

**Comment by strahe** [comment]
```go
ap := plugin.NewPrometheusAlertManager(cfg)
err := ap.SendAlert(&plugin.AlertPayload{
	Time:     time.Now(),
	Severity: "critical",
	Source:   "curio",
	Summary:  "Curio Alert",
	Details: map[string]interface{}{
		"test": "test",
	},
})
```
In Prometheus Alertmanager:

image

**Review by LexLuthr — APPROVED** [review]
Great job!! Thank you for the contribution.

**Pull request merged**
